### ISSUE TITLE
need hackage & stackage support

### ISSUE THREAD

**Issue by delta4d** [zjulug/mirrors-issue-tracker#16]
like:
- https://mirrors.tuna.tsinghua.edu.cn/help/stackage/
- https://mirrors.tuna.tsinghua.edu.cn/help/hackage/

**Comment by vxst** [comment]
Currently adding them

**Comment by vxst** [comment]
Add added, please check whether these mirrors are working:
```
http://mirrors.zju.edu.cn/stackage/
http://mirrors.zju.edu.cn/hackage/
```
If all is good, please close the issue and I will add them to the index.

**Comment by delta4d** [comment]
Thanks, it works!

### hackage

```
-- ~/.cabal/config
repository mirrors.zju.edu.cn
  url: http://mirrors.zju.edu.cn/hackage
```

```
# ~/.stack/config.yaml
package-indices:
  - name: ZJU
    download-prefix: http://mirrors.zju.edu.cn/hackage/package/
    http: http://mirrors.zju.edu.cn/hackage/00-index.tar.gz
```

### stackage

```
# ~/.stack/config.yaml
setup-info: "http://mirrors.zju.edu.cn/stackage/stack-setup.yaml"
urls:
  latest-snapshot: http://mirrors.zju.edu.cn/stackage/snapshots.json
  lts-build-plans: http://mirrors.zju.edu.cn/stackage/lts-haskell/
  nightly-build-plans: http://mirrors.zju.edu.cn/stackage/stackage-nightly/
```

### refs

1. http://hackage.haskell.org/
2. https://www.stackage.org/
3. https://mirrors.tuna.tsinghua.edu.cn/help/stackage/
4. https://mirrors.tuna.tsinghua.edu.cn/help/hackage/
